/**
 * Elementor-like Style Manager Configuration for GrapeJS
 * Organized into sectors matching Elementor's style panel
 */

export const styleManagerConfig = {
  appendTo: '.styles-container',
  sectors: [
    {
      name: 'Typography',
      open: true,
      properties: [
        {
          property: 'font-family',
          type: 'select',
          defaults: 'Inter, sans-serif',
          options: [
            { id: 'Inter, sans-serif', label: 'Inter' },
            { id: 'Roboto, sans-serif', label: 'Roboto' },
            { id: 'Open Sans, sans-serif', label: 'Open Sans' },
            { id: 'Lato, sans-serif', label: 'Lato' },
            { id: 'Montserrat, sans-serif', label: 'Montserrat' },
            { id: 'Poppins, sans-serif', label: 'Poppins' },
            { id: 'Playfair Display, serif', label: 'Playfair Display' },
            { id: 'Merriweather, serif', label: 'Merriweather' },
            { id: 'Georgia, serif', label: 'Georgia' },
            { id: 'Arial, sans-serif', label: 'Arial' },
            { id: 'Helvetica, sans-serif', label: 'Helvetica' },
            { id: 'Times New Roman, serif', label: 'Times New Roman' },
          ],
        },
        {
          property: 'font-size',
          type: 'slider',
          defaults: '16px',
          min: 8,
          max: 120,
          step: 1,
          units: ['px', 'em', 'rem', '%', 'vw'],
        },
        {
          property: 'font-weight',
          type: 'select',
          defaults: '400',
          options: [
            { id: '100', label: 'Thin (100)' },
            { id: '200', label: 'Extra Light (200)' },
            { id: '300', label: 'Light (300)' },
            { id: '400', label: 'Regular (400)' },
            { id: '500', label: 'Medium (500)' },
            { id: '600', label: 'Semi Bold (600)' },
            { id: '700', label: 'Bold (700)' },
            { id: '800', label: 'Extra Bold (800)' },
            { id: '900', label: 'Black (900)' },
          ],
        },
        {
          property: 'line-height',
          type: 'slider',
          defaults: '1.5',
          min: 0.5,
          max: 4,
          step: 0.1,
          units: ['', 'px', 'em'],
        },
        {
          property: 'letter-spacing',
          type: 'slider',
          defaults: '0px',
          min: -10,
          max: 30,
          step: 0.5,
          units: ['px', 'em'],
        },
        {
          property: 'color',
          type: 'color',
          defaults: '#333333',
        },
        {
          property: 'text-align',
          type: 'radio',
          defaults: 'left',
          options: [
            { id: 'left', label: 'Left', className: 'fa fa-align-left' },
            { id: 'center', label: 'Center', className: 'fa fa-align-center' },
            { id: 'right', label: 'Right', className: 'fa fa-align-right' },
            { id: 'justify', label: 'Justify', className: 'fa fa-align-justify' },
          ],
        },
        {
          property: 'text-transform',
          type: 'select',
          defaults: 'none',
          options: [
            { id: 'none', label: 'None' },
            { id: 'uppercase', label: 'UPPERCASE' },
            { id: 'lowercase', label: 'lowercase' },
            { id: 'capitalize', label: 'Capitalize' },
          ],
        },
        {
          property: 'text-decoration',
          type: 'select',
          defaults: 'none',
          options: [
            { id: 'none', label: 'None' },
            { id: 'underline', label: 'Underline' },
            { id: 'line-through', label: 'Line Through' },
            { id: 'overline', label: 'Overline' },
          ],
        },
      ],
    },
    {
      name: 'Spacing',
      open: false,
      properties: [
        {
          property: 'margin',
          type: 'composite',
          properties: [
            { property: 'margin-top', type: 'slider', min: -100, max: 200, units: ['px', 'em', 'rem', '%', 'auto'] },
            { property: 'margin-right', type: 'slider', min: -100, max: 200, units: ['px', 'em', 'rem', '%', 'auto'] },
            { property: 'margin-bottom', type: 'slider', min: -100, max: 200, units: ['px', 'em', 'rem', '%', 'auto'] },
            { property: 'margin-left', type: 'slider', min: -100, max: 200, units: ['px', 'em', 'rem', '%', 'auto'] },
          ],
        },
        {
          property: 'padding',
          type: 'composite',
          properties: [
            { property: 'padding-top', type: 'slider', min: 0, max: 200, units: ['px', 'em', 'rem', '%'] },
            { property: 'padding-right', type: 'slider', min: 0, max: 200, units: ['px', 'em', 'rem', '%'] },
            { property: 'padding-bottom', type: 'slider', min: 0, max: 200, units: ['px', 'em', 'rem', '%'] },
            { property: 'padding-left', type: 'slider', min: 0, max: 200, units: ['px', 'em', 'rem', '%'] },
          ],
        },
      ],
    },
    {
      name: 'Size',
      open: false,
      properties: [
        {
          property: 'width',
          type: 'slider',
          min: 0,
          max: 2000,
          units: ['px', '%', 'vw', 'auto'],
        },
        {
          property: 'height',
          type: 'slider',
          min: 0,
          max: 2000,
          units: ['px', '%', 'vh', 'auto'],
        },
        {
          property: 'min-width',
          type: 'slider',
          min: 0,
          max: 2000,
          units: ['px', '%', 'vw'],
        },
        {
          property: 'max-width',
          type: 'slider',
          min: 0,
          max: 2000,
          units: ['px', '%', 'vw', 'none'],
        },
        {
          property: 'min-height',
          type: 'slider',
          min: 0,
          max: 2000,
          units: ['px', '%', 'vh'],
        },
        {
          property: 'max-height',
          type: 'slider',
          min: 0,
          max: 2000,
          units: ['px', '%', 'vh', 'none'],
        },
      ],
    },
    {
      name: 'Background',
      open: false,
      properties: [
        {
          property: 'background-color',
          type: 'color',
          defaults: 'transparent',
        },
        {
          property: 'background-image',
          type: 'file',
        },
        {
          property: 'background-size',
          type: 'select',
          defaults: 'auto',
          options: [
            { id: 'auto', label: 'Auto' },
            { id: 'cover', label: 'Cover' },
            { id: 'contain', label: 'Contain' },
            { id: '100% 100%', label: 'Full' },
          ],
        },
        {
          property: 'background-position',
          type: 'select',
          defaults: 'center center',
          options: [
            { id: 'left top', label: 'Top Left' },
            { id: 'center top', label: 'Top Center' },
            { id: 'right top', label: 'Top Right' },
            { id: 'left center', label: 'Center Left' },
            { id: 'center center', label: 'Center' },
            { id: 'right center', label: 'Center Right' },
            { id: 'left bottom', label: 'Bottom Left' },
            { id: 'center bottom', label: 'Bottom Center' },
            { id: 'right bottom', label: 'Bottom Right' },
          ],
        },
        {
          property: 'background-repeat',
          type: 'select',
          defaults: 'no-repeat',
          options: [
            { id: 'no-repeat', label: 'No Repeat' },
            { id: 'repeat', label: 'Repeat' },
            { id: 'repeat-x', label: 'Repeat X' },
            { id: 'repeat-y', label: 'Repeat Y' },
          ],
        },
        {
          property: 'background-attachment',
          type: 'select',
          defaults: 'scroll',
          options: [
            { id: 'scroll', label: 'Scroll' },
            { id: 'fixed', label: 'Fixed' },
          ],
        },
      ],
    },
    {
      name: 'Border',
      open: false,
      properties: [
        {
          property: 'border-width',
          type: 'slider',
          defaults: '0px',
          min: 0,
          max: 20,
          units: ['px'],
        },
        {
          property: 'border-style',
          type: 'select',
          defaults: 'none',
          options: [
            { id: 'none', label: 'None' },
            { id: 'solid', label: 'Solid' },
            { id: 'dashed', label: 'Dashed' },
            { id: 'dotted', label: 'Dotted' },
            { id: 'double', label: 'Double' },
            { id: 'groove', label: 'Groove' },
            { id: 'ridge', label: 'Ridge' },
          ],
        },
        {
          property: 'border-color',
          type: 'color',
          defaults: '#000000',
        },
        {
          property: 'border-radius',
          type: 'composite',
          properties: [
            { property: 'border-top-left-radius', type: 'slider', min: 0, max: 100, units: ['px', '%'] },
            { property: 'border-top-right-radius', type: 'slider', min: 0, max: 100, units: ['px', '%'] },
            { property: 'border-bottom-right-radius', type: 'slider', min: 0, max: 100, units: ['px', '%'] },
            { property: 'border-bottom-left-radius', type: 'slider', min: 0, max: 100, units: ['px', '%'] },
          ],
        },
      ],
    },
    {
      name: 'Effects',
      open: false,
      properties: [
        {
          property: 'box-shadow',
          type: 'stack',
          properties: [
            { property: 'box-shadow-h', type: 'slider', min: -50, max: 50, defaults: '0px' },
            { property: 'box-shadow-v', type: 'slider', min: -50, max: 50, defaults: '0px' },
            { property: 'box-shadow-blur', type: 'slider', min: 0, max: 100, defaults: '0px' },
            { property: 'box-shadow-spread', type: 'slider', min: -50, max: 50, defaults: '0px' },
            { property: 'box-shadow-color', type: 'color', defaults: 'rgba(0,0,0,0.2)' },
            { property: 'box-shadow-type', type: 'select', defaults: '', options: [{ id: '', label: 'Outer' }, { id: 'inset', label: 'Inner' }] },
          ],
        },
        {
          property: 'opacity',
          type: 'slider',
          defaults: '1',
          min: 0,
          max: 1,
          step: 0.05,
        },
        {
          property: 'transition',
          type: 'composite',
          properties: [
            { property: 'transition-property', type: 'select', defaults: 'all', options: [{ id: 'all', label: 'All' }, { id: 'transform', label: 'Transform' }, { id: 'opacity', label: 'Opacity' }, { id: 'background', label: 'Background' }] },
            { property: 'transition-duration', type: 'slider', defaults: '0.3s', min: 0, max: 2, step: 0.1, units: ['s'] },
            { property: 'transition-timing-function', type: 'select', defaults: 'ease', options: [{ id: 'ease', label: 'Ease' }, { id: 'linear', label: 'Linear' }, { id: 'ease-in', label: 'Ease In' }, { id: 'ease-out', label: 'Ease Out' }, { id: 'ease-in-out', label: 'Ease In Out' }] },
          ],
        },
      ],
    },
    {
      name: 'Layout',
      open: false,
      properties: [
        {
          property: 'display',
          type: 'select',
          defaults: 'block',
          options: [
            { id: 'block', label: 'Block' },
            { id: 'inline', label: 'Inline' },
            { id: 'inline-block', label: 'Inline Block' },
            { id: 'flex', label: 'Flex' },
            { id: 'grid', label: 'Grid' },
            { id: 'none', label: 'None' },
          ],
        },
        {
          property: 'position',
          type: 'select',
          defaults: 'static',
          options: [
            { id: 'static', label: 'Static' },
            { id: 'relative', label: 'Relative' },
            { id: 'absolute', label: 'Absolute' },
            { id: 'fixed', label: 'Fixed' },
            { id: 'sticky', label: 'Sticky' },
          ],
        },
        {
          property: 'top',
          type: 'slider',
          min: -500,
          max: 500,
          units: ['px', '%', 'auto'],
        },
        {
          property: 'right',
          type: 'slider',
          min: -500,
          max: 500,
          units: ['px', '%', 'auto'],
        },
        {
          property: 'bottom',
          type: 'slider',
          min: -500,
          max: 500,
          units: ['px', '%', 'auto'],
        },
        {
          property: 'left',
          type: 'slider',
          min: -500,
          max: 500,
          units: ['px', '%', 'auto'],
        },
        {
          property: 'z-index',
          type: 'slider',
          min: -10,
          max: 1000,
          defaults: 'auto',
        },
        {
          property: 'overflow',
          type: 'select',
          defaults: 'visible',
          options: [
            { id: 'visible', label: 'Visible' },
            { id: 'hidden', label: 'Hidden' },
            { id: 'scroll', label: 'Scroll' },
            { id: 'auto', label: 'Auto' },
          ],
        },
      ],
    },
    {
      name: 'Flexbox',
      open: false,
      properties: [
        {
          property: 'flex-direction',
          type: 'select',
          defaults: 'row',
          options: [
            { id: 'row', label: 'Row' },
            { id: 'row-reverse', label: 'Row Reverse' },
            { id: 'column', label: 'Column' },
            { id: 'column-reverse', label: 'Column Reverse' },
          ],
        },
        {
          property: 'flex-wrap',
          type: 'select',
          defaults: 'nowrap',
          options: [
            { id: 'nowrap', label: 'No Wrap' },
            { id: 'wrap', label: 'Wrap' },
            { id: 'wrap-reverse', label: 'Wrap Reverse' },
          ],
        },
        {
          property: 'justify-content',
          type: 'select',
          defaults: 'flex-start',
          options: [
            { id: 'flex-start', label: 'Start' },
            { id: 'flex-end', label: 'End' },
            { id: 'center', label: 'Center' },
            { id: 'space-between', label: 'Space Between' },
            { id: 'space-around', label: 'Space Around' },
            { id: 'space-evenly', label: 'Space Evenly' },
          ],
        },
        {
          property: 'align-items',
          type: 'select',
          defaults: 'stretch',
          options: [
            { id: 'flex-start', label: 'Start' },
            { id: 'flex-end', label: 'End' },
            { id: 'center', label: 'Center' },
            { id: 'stretch', label: 'Stretch' },
            { id: 'baseline', label: 'Baseline' },
          ],
        },
        {
          property: 'align-content',
          type: 'select',
          defaults: 'stretch',
          options: [
            { id: 'flex-start', label: 'Start' },
            { id: 'flex-end', label: 'End' },
            { id: 'center', label: 'Center' },
            { id: 'stretch', label: 'Stretch' },
            { id: 'space-between', label: 'Space Between' },
            { id: 'space-around', label: 'Space Around' },
          ],
        },
        {
          property: 'gap',
          type: 'slider',
          defaults: '0px',
          min: 0,
          max: 100,
          units: ['px', 'em', 'rem', '%'],
        },
      ],
    },
  ],
};

export default styleManagerConfig;
