import React, {useEffect, useState} from 'react';
import Head from 'next/head';
import { Box } from '@mui/system';
import Report from '../../components/Report';
import { DropZone } from '../../components/dropzone';

export default function Home({}) {

    return (
    <div>
        <Head>
        <title>File Upload Components</title>
        <meta name="description" content="Generated by AuthScape" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <Box>
            <DropZone />
        </Box>
    </div>
    )
}
