// Auto-generated by AuthScape - Do not edit manually.
// Exists so /signin-oidc returns HTTP 200 (not the Next.js 404 page).
// Required for Webkit/Safari: useSearchParams() doesn't hydrate on the 404
// page in Webkit, so the PKCE 'code' query param is never read and sign-in
// silently stalls. With this real page in place, AuthScapeApp's
// signInValidator picks up the code and completes the exchange normally.
export default function SignInOidc() {
  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "60vh",
        fontFamily: "system-ui, -apple-system, Segoe UI, sans-serif",
        color: "#666",
      }}
    >
      Signing you in…
    </div>
  );
}
