// Auto-generated by AuthScape - Do not edit manually
import { Sitemap, createSitemapHandler } from 'authscape/src/lib/sitemap';

export default Sitemap;

export const getServerSideProps = createSitemapHandler(process.env.apiUri);
